# Generated by Django 3.2.19 on 2023-08-23 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parent_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidationBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('admin_notes', models.TextField()),
                ('organizations', models.ManyToManyField(to='organizations.Organization')),
                ('validators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(to='platform_global_teacher_campus.CourseCategory')),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_overviews.courseoverview')),
                ('current_validation_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('validation_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_global_teacher_campus.validationbody')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRejectionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_notes', models.TextField()),
                ('is_active', models.BooleanField()),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validation_body', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_global_teacher_campus.validationbody')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationProcessEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('reason', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_global_teacher_campus.validationrejectionreason')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validation_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_global_teacher_campus.validationprocess')),
            ],
        ),
    ]
