# Generated by Django 3.2.19 on 2023-08-24 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_historicalorganizationcourse'),
        ('platform_global_teacher_campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_global_teacher_campus.coursecategory'),
        ),
        migrations.AlterField(
            model_name='validationbody',
            name='admin_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='validationprocess',
            name='current_validation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validationprocessevent',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_global_teacher_campus.validationrejectionreason'),
        ),
        migrations.AlterField(
            model_name='validationrules',
            name='admin_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='validationrules',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='validationrules',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validationrules',
            name='validation_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_global_teacher_campus.validationbody'),
        ),
    ]
