# Generated by Django 3.2.19 on 2023-08-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_global_teacher_campus', '0003_auto_20230824_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrejectionreason',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
