# Generated by Django 3.2.19 on 2023-08-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_global_teacher_campus', '0004_alter_validationrejectionreason_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrules',
            name='permission_type',
            field=models.CharField(choices=[('org_excluded', 'Organization Excluded'), ('org_exempt', 'Organization Exempt'), ('user_exempt', 'User Exempt'), ('vb_exempt', 'Validation Body Exempt')], default='org_excluded', max_length=15),
        ),
    ]
