# Generated by Django 3.2.19 on 2023-09-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_global_teacher_campus', '0005_validationrules_permission_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='validationbody',
            options={'verbose_name_plural': 'Validation Bodies'},
        ),
        migrations.AlterModelOptions(
            name='validationprocess',
            options={'verbose_name_plural': 'Validation Processes'},
        ),
        migrations.AlterModelOptions(
            name='validationprocessevent',
            options={'verbose_name_plural': 'Validation Process Events'},
        ),
        migrations.AlterModelOptions(
            name='validationrejectionreason',
            options={'verbose_name_plural': 'Validation Rejection Reasons'},
        ),
        migrations.AlterModelOptions(
            name='validationrules',
            options={'verbose_name_plural': 'Validation Rules'},
        ),
    ]
