# Generated by Django 3.2.19 on 2023-09-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_global_teacher_campus', '0006_auto_20230911_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationprocessevent',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
