# Generated by Django 3.2.19 on 2023-09-21 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platform_global_teacher_campus', '0007_rename_create_at_validationprocessevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationbody',
            name='validators',
            field=models.ManyToManyField(related_name='validation_bodies', to=settings.AUTH_USER_MODEL),
        ),
    ]
